# Le dice a Prometheus que recolecte las métricas de esta app
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-api
spec:
  selector:
    matchLabels:
      app: python-api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
